apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-prboard.fullname" . }}
  labels:
    {{- include "simple-prboard.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.configMapData | indent 4 }}

