apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-prboard.fullname" . }}
  labels:
    {{- include "simple-prboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "simple-prboard.selectorLabels" . | nindent 4 }}
